import {chromium} from '/Users/zhuo/.cache/trader-dna-v48-manual/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const base=process.env.BASE||'http://127.0.0.1:4346';
const out=process.env.OUT||'/Users/zhuo/.cache/trader-dna-detail-04/qa/portrait-perf';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const ctx=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:2});
const p=await ctx.newPage();
const cdp=await ctx.newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});
await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:200,downloadThroughput:250*1024/8,uploadThroughput:100*1024/8});
const requests=[],errors=[];
p.on('request',r=>{if(/portrait-cards|george-soros|paul-tudor/i.test(r.url()))requests.push({kind:'request',url:r.url(),t:Date.now()})});
p.on('response',r=>{if(/portrait-cards|george-soros|paul-tudor/i.test(r.url()))requests.push({kind:'response',url:r.url(),status:r.status(),t:Date.now()})});
p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/scan01.html?start=scan01',{waitUntil:'domcontentloaded',timeout:30000});
await p.waitForFunction(()=>document.querySelector('.question-index')?.textContent.trim()==='Q01',{timeout:30000});
for(let q=1;q<=18;q++){
 const choice=await p.evaluate(q=>{const x=QUESTIONS.find(x=>x.id===q);return ['直覺','出擊','守界','變陣','敏銳','獨行'].includes(x.aPole)?'A':'B'},q);
 await p.locator('.option[data-choice="'+choice+'"]').click();
 if(q<18)await p.waitForFunction(n=>document.querySelector('.question-index')?.textContent.trim()==='Q'+String(n).padStart(2,'0'),q+1);
}const revealAt=Date.now();await p.locator('.reveal').waitFor({state:'attached',timeout:10000});
await p.locator('.result').waitFor({state:'attached',timeout:12000});const resultAt=Date.now();
await p.waitForFunction(()=>document.querySelectorAll('.v4-same-type .v3-person-portrait.has-image').length===2,{timeout:12000});const readyAt=Date.now();
const type=await p.locator('.result .code').innerText();
const sources=await p.locator('.v4-same-type img').evaluateAll(xs=>xs.map(x=>({src:x.currentSrc||x.src,w:x.naturalWidth,h:x.naturalHeight,complete:x.complete})));
const originals=requests.filter(x=>x.kind==='request'&&/george-soros-local\.jpg|paul-tudor-jones-2006\.jpg/.test(x.url));
const cards=requests.filter(x=>x.kind==='request'&&/portrait-cards/.test(x.url));
const report={base,type,revealToResultMs:resultAt-revealAt,resultToPortraitReadyMs:readyAt-resultAt,revealToPortraitReadyMs:readyAt-revealAt,cardRequests:cards,originalCardRequests:originals,sources,errors,result:'PASS'};
if(type!=='IAGF')throw Error('unexpected type '+type);
if(sources.length!==2||sources.some(x=>!x.src.includes('/portrait-cards/')||!x.complete||!x.w))throw Error('optimized sources missing '+JSON.stringify(sources));
if(originals.length)throw Error('full originals requested for inline cards '+JSON.stringify(originals));
if(readyAt-resultAt>700)throw Error('portrait reveal too late after result: '+(readyAt-resultAt));
if(errors.length)throw Error('page errors '+errors.join('; '));
await p.locator('.v4-same-type').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/same-type-mobile.png'});
await fs.writeFile(out+'/portrait-perf.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
await browser.close();